services:
  # PostgreSQL Database
  db:
    image: postgres:latest
    container_name: kaleidoscope_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kaleidoscope
    ports:
      - "5432:5432"

  # MinIO Storage
  minio:
    image: minio/minio:latest
    container_name: kaleidoscope_minio
    command: server /data --console-address ":9001" 
    environment:
      - MINIO_ROOT_USER=kaleidoscope
      - MINIO_ROOT_PASSWORD=kaleidoscope@minio123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  # Redis Cache
  redis:
    image: redis:latest
    container_name: kaleidoscope_redis
    ports:
      - "6379:6379"

volumes:
  db_data:
  minio_data:
