name: Build and Lint

on:
  push:
    branches:
      - '**' # Run on all branches
  pull_request:
    branches:
      - '**'

jobs:
  Build-and-Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Run Linter
        run: pnpm lint

      - name: Build Project
        run: pnpm build
